
version: '3.4'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    depends_on:
      - postgres
    ports:
      - "3002:3000"

  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "zadanie_development"
      POSTGRES_USER: "evgeny"
      POSTGRES_PASSWORD: "123"
    volumes:
      - .:/docker-entrypoint-initdb.d
    ports:
      - "5434:5432"
  
