
version: '3.4'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "3000:3000"
    env_file: .env
    environment:
      RAILS_ENV: development

  db:
    image: postgres:12.1
  