default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME") {'zadanie_development'}%>
  username: <%= ENV.fetch("DATABASE_USER") {'evgeny'} %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") {123} %>
  host: 127.0.0.1 #<%= ENV.fetch("DATABASE_HOST") {123} %>
  port: 5432


test:
  <<: *default
  database: <%= ENV.fetch("TEST_DATABASE_NAME") {'zadanie_test'} %>
  username: <%= ENV.fetch("DATABASE_USER") {'evgeny'} %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") {123}%>

#
# production:
#   adapter: postgresql
#   encoding: unicode
#   database: zadanie_production
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#   username: evgeny
#   password: <%= ENV["ZADANIE_DATABASE_PASSWORD"] %>

production:
  <<: *default
  database: <%= ENV["DATABASE_NAME"] %>
  username: <%= ENV["DATABASE_USER"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>

